platform :ios, '7.0'
pod 'NYXImagesKit',	'2.3'
pod 'NJKWebViewProgress', '0.2'
pod 'AFNetworking',     '2.4.1'
pod 'MMDrawerController', '0.5.1'
pod 'TSMessages',       '0.9.4'
pod 'HTProgressHUD',    '0.1.1'
pod 'RMSwipeTableViewCell','0.5.5'
pod 'NSDate+TimeAgo',   '1.0.2'
pod 'MagicalRecord',	'2.2'
pod 'KGStatusBar',	'1.0'
pod 'StyledPageControl', '1.0'
pod 'SDWebImage', 	'3.7.1'
#pod 'LBBlurredImage',	'0.2.0'
pod 'BlocksKit',	'2.2.5'
#pod 'AMSmoothAlert',	'1.1'
#pod 'FXBlurView',	'1.6.3'

